import type { Metadata } from "next";
import { Nunito } from 'next/font/google';
import "./globals.css";

// Nunito Font Configuration
const nunito = Nunito({
  subsets: ['latin', 'latin-ext'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-nunito',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Claimly",
  description: "Generated by create next app",
};

import LayoutWrapper from "@/components/shared/LayoutWrapper";
import ReduxProvider from "@/store/ReduxProvider";
import { Toaster } from "sonner";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={nunito.variable}>
      <body
        className={`${nunito.variable} antialiased`}
      >
        <ReduxProvider>
          <LayoutWrapper>
            <Toaster position="top-right" richColors />
            {children}
          </LayoutWrapper>
        </ReduxProvider>

      </body>
    </html>
  );
}
