import type { Metadata } from "next";
import { Nunito } from 'next/font/google';
import "./globals.css";
{/* <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"></meta> */}

// Nunito Font Configuration
const nunito = Nunito({
  subsets: ['latin', 'latin-ext'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-nunito',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Claimly",
  description: "Generated by create next app",
};

import LayoutWrapper from "@/components/shared/LayoutWrapper";
import ReduxProvider from "@/store/ReduxProvider";
import { Toaster } from "sonner";
import PrivateRoute from "@/PrivateRoute/PrivateRoute";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={nunito.variable} suppressHydrationWarning>
      <body
        className={`${nunito.variable} antialiased`}
        suppressHydrationWarning
      >
        <ReduxProvider>
          <PrivateRoute>
            <LayoutWrapper>
              <Toaster position="top-right" richColors />
              {children}
            </LayoutWrapper>
          </PrivateRoute>
        </ReduxProvider>

      </body>
    </html>
  );
}
